import type { Metadata } from "next";
import "./globals.css";
import { Prompt } from "@next/font/google";

const prompt = Prompt({
  subsets: ["thai"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={prompt.className}>{children}</body>
    </html>
  );
}
